### ISSUE TITLE
Add support for `LOCATE` scalar function

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/elasticsearch-virtual-schema#29]
ElasticSearch supports `LOCATE`, but not with a negative position as Exasol does.

Perhaps we can write an adaptation for it.

https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/locate.htm#Locate

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-string.html#sql-functions-string-locate

**Comment by redcatbear** [comment]
Shelved.
