### ISSUE TITLE
Unknown Virtual Schema Adapter "UNKNOWN" requested.

### ISSUE THREAD

**Issue by lestremm** [exasol/elasticsearch-virtual-schema#38]
Hey Guys,

just would like to start with your new ES adapter (great idea!) but unfortunately the adapter didn't work on my site. If followed these instructions

[https://github.com/exasol/elasticsearch-virtual-schema/blob/main/doc/dialects/elasticsearch_sql_user_guide.md](url)

and add the latestes jars to bucket fs in the default folder. When I run

`curl http://r:read@192.168.178.41:1234/default`

the files are there:
`virtual-schema-dist-8.0.0-elasticsearch-1.0.0.jar`
`x-pack-sql-jdbc-7.12.0.jar`

Afterwards I've created the adapter by

`CREATE OR REPLACE JAVA ADAPTER SCRIPT ELASTIC.ES_ADAPTER AS`
`  %scriptclass com.exasol.adapter.RequestDispatcher;`
`  %jar /buckets/bfsdefault/default/virtual-schema-dist-8.0.0-elasticsearch-1.0.0.jar;`
`  %jar /buckets/bfsdefault/default/x-pack-sql-jdbc-7.12.0.jar;`
`/`

and of course I create the connection with

`CREATE OR REPLACE CONNECTION ELASTIC_CONNECTION
TO 'jdbc:es://http://192.168.178.29:9205/';;`

But when I try to create the VS with

`CREATE VIRTUAL SCHEMA VIRTUAL_SCHEMA_TEST USING ELASTIC.ES_ADAPTER WITH
  CONNECTION_NAME = 'ELASTIC_CONNECTION'
  SCHEMA_NAME     = 'ELASTIC';`

I receive the above error. Here is the full stack trace:

`SQL-Fehler [22002]: VM error: `
`java.lang.IllegalArgumentException: Unknown Virtual Schema Adapter "UNKNOWN" requested. Currently registered Virtual Schema Adapter factories: "ES"`
`Stack trace:`
`com.exasol.adapter.AdapterRegistry.getAdapterForName(AdapterRegistry.java:76)`
`com.exasol.adapter.RequestDispatcher.findResponsibleAdapter(RequestDispatcher.java:62)`
`com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:51)`
`com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)`
`java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
`java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`java.base/java.lang.reflect.Method.invoke(Method.java:566)`
`com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:95) (Session: 1696051372399491389)`

Did I skip a step or is it a bug? I've used the community edition 6.2.4. I would really like to work with this feature. Thanx in advance.

**Comment by redcatbear** [comment]
I think this VS still needs the old `DIALECT` property when creating the Virtual Schema.

Try:
```sql
CREATE VIRTUAL SCHEMA VIRTUAL_SCHEMA_TEST
USING ELASTIC.ES_ADAPTER
WITH
	CONNECTION_NAME = 'ELASTIC_CONNECTION'
	DIALECT = 'ES'
	SCHEMA_NAME = 'ELASTIC';
```

Also remote logging might help: https://github.com/exasol/virtual-schema-common-jdbc/blob/main/doc/development/remote_logging.md

**Comment by chiaradiamarcelo** [comment]
Hi @lestremm ,

as @redcatbear said, the `SQL_DIALECT` was missing.

In the [2.0.0 release](https://github.com/exasol/elasticsearch-virtual-schema/releases/tag/2.0.0) of the ElasticSearch Virtual Schema this property is not required anymore.

**Comment by lestremm** [comment]
Thx for your help! I've updated to the newest version and this error doenst popup anymore. I cann successfully create the virtual schema now but if I start a request I get the following error:

`SQL-Fehler [ETL-1]: No default DRIVER registered for jdbc:es://http://192.168.2.199:9205/. Please specify DRIVER or add a default via EXAoperation (Session: 1696591306360303402)`

In the User Manuel there was no section about adding the x pack jar to ExaOperations but I've tried this with the following parameter:

`Main Class: org.elasticsearch.xpack.sql.jdbc.EsDriver`
`Prefix: jdbc:es`
`Files: x-pack-sql-jdbc-7.12.0.jar`

but still the folloing error pop up:

`SQL-Fehler [ETL-5]: JDBC-Client-Error: Failed loading driver 'org.elasticsearch.xpack.sql.jdbc.EsDriver': null, access denied ("java.lang.RuntimePermission" "getProtectionDomain") (Session: 1696591306360303402)`

Is this step really necessary and should I try without security manager or how did you folks managed this issue?

**Comment by redcatbear** [comment]
@lestremm, please check whether
```sql
EXPLAIN VIRTUAL <sql-statement>
```
works. If that works fine, your Virtual Schema is set up correctly. In that case the remaining issue is in the interworking of the ExaLoader and the Driver.

ExaLoader is the component that runs the `IMPORT` commands created by the Virtual Schema. Your new error looks like the driver request a security feature that is not enabled in ExaLoader's security policy. In which case you indeed need to disable the security manager in ExaOperation.

**Comment by chiaradiamarcelo** [comment]
Hi @lestremm 

As @redcatbear said, you need to disable the Security Manager, as stated in the [user guide](https://github.com/exasol/elasticsearch-virtual-schema/blob/main/doc/user_guide/elasticsearch_sql_user_guide.md).

**Comment by lestremm** [comment]
Thx for your help. I've disabled the security manager and I can request data from ES successfully! Still a great feature :-) I think I've skipped this point from the doc because it is raised up at the very beginning and the uploading of the JDBC driver in ExaOperations is explained in the general Virtual Schema guide but not in the ES user guide. Maybe it would helpful if you mention that the JDBC driver has to be uploaded in ExaOperation under "Uploading the JDBC Driver to EXAOperation" as well.

I'm not sure if it is a general limition of virtual schemas but if I try to create a VIEW on my SELECT statement like

`CREATE OR REPLACE VIEW ES_TEST.VW_TEST AS`
`SELECT "key", "kpi" FROM "VIRTUAL_SCHEMA_TEST"."myindex";`

I receive the following error:

`QL-Fehler [42500]: insufficient privileges: SELECT on table myindex`

Are views generally not supported in Virtual Schemas (found nothing about this point in the doc or FAQ) or is it really a privileges issue?

**Comment by chiaradiamarcelo** [comment]
Hi @lestremm ,
thanks for the suggestion.

Views are supported in the Virtual Schemas. Your statement should work.
It seems to be a matter of privileges, so make sure the user has the right access permissions to your `myindex` table in the virtual schema.

**Comment by chiaradiamarcelo** [comment]
Closing as solved
