### ISSUE TITLE
Elastic tables with "." in the name cannot be queried

### ISSUE THREAD

**Issue by Ronaldvr** [exasol/elasticsearch-virtual-schema#42]
Elastic tables with "." in the name get properly translated to "/" on read and are visible in the virtual schema table view, however they cannot be queried, since the "/"is not translated back.

**Comment by chiaradiamarcelo** [comment]
Hi @Ronaldvr , thanks for the feedback.

That is indeed strange.

Please make sure that:
1 - The nested field you want to query exists in the ElasticSearch index. (e.g. "nested_field.value")
2 - The nested field you want to query exists in the ElasticSearch Virtual Schema in the Exasol database. (e.g. "nested_field/value")
3 - When querying, make sure to use quotes as ElasticSearch is case sensitive and if you don't use quotes Exasol will convert the identifiers to uppercase. (e.g. `SELECT "nested_field/value" FROM "<ElasticSearch_Virtual_Schema_Name>"."<Table_to_query>";`)See [the user guide](https://github.com/exasol/elasticsearch-virtual-schema/blob/main/doc/user_guide/elasticsearch_sql_user_guide.md#elasticsearch-identifiers) for more information about it.
4 - Try to perform the same query but adding `EXPLAIN VIRTUAL` at the beginning. (e.g. `EXPLAIN VIRTUAL SELECT "nested_field/value" FROM "<ElasticSearch_Virtual_Schema_Name>"."<Table_to_query>";`)

If this does not work, please provide the logs/error messages.

Thanks!

**Comment by redcatbear** [comment]
@Ronaldvr, please check the suggested investigation steps listed by @chiaradiamarcelo and let us know the result.

**Comment by redcatbear** [comment]
Closing this ticket after 22 day without user response.
