### ISSUE TITLE
Update to VSCJDBC 10.0.1

### ISSUE THREAD

**Issue by ckunki** [exasol/elasticsearch-virtual-schema#63]
Update dependencies to use enhanced Datatype Detection For Result Sets from virtual-schemas-common-jdbc

**Comment by kaklakariada** [comment]
Will be done in #60

**Comment by redcatbear** [comment]
This is what I see on main in the POM:
```xml
<vscjdbc.version>10.1.0</vscjdbc.version>
```

I think this one is not a duplicate and still open, @kaklakariada.

**Comment by kaklakariada** [comment]
In #60 we upgraded to VSCJDBC 10.1.0, so we can close this.
