### ISSUE TITLE
Remove test workaround for issue with invalid DB results

### ISSUE THREAD

**Issue by kaklakariada** [exasol/elasticsearch-virtual-schema#65]
Exasol 7.1.17 returns wrong values for `EXTRACT SECOND FROM`:

```
SELECT EXTRACT(SECOND FROM CAST('2018-02-19 10:23:27' AS TIMESTAMP))
FROM VIRTUAL_SCHEMA."index";
```

This returns 0.027 instead of the expected value 27.

Also see integration test `testExtractSecond()`:

```
assertExtract("SECOND").withValues("2018-02-19T10:23:27Z").withResult(27).verify()
```

This is a bug in Exasol 7.1.17.

Currently the expected value is set to 0.027 to make the test pass. Once a new DB release with a fix is available we need to upgrade and adapt the test case.

See also #60 and #64.

**Comment by redcatbear** [comment]
We don't invest time into 7.1 in this case anymore.
